openapi: 3.0.3
info:
  title: GDPR-Friendly KV Store
  description: >
    API for managing data subjects and their key-value records with GDPR compliance built in.
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy

  /subjects:
    post:
      summary: Create a new subject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                residency:
                  type: string
                  example: eu
                identifiers:
                  type: object
                  example: { email: "alice@example.com" }
      responses:
        '201':
          description: Subject created
    get:
      summary: List all subjects
      responses:
        '200':
          description: List of subjects

  /subjects/{subjectId}:
    get:
      summary: Get a subject by ID
      parameters:
        - in: path
          name: subjectId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Subject found
        '404':
          description: Not found

  /kv/{subjectId}/{key}:
    put:
      summary: Store or update a key-value record for a subject
      parameters:
        - in: path
          name: subjectId
          required: true
          schema:
            type: string
        - in: path
          name: key
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: object
                  example: { city: "Berlin" }
                purpose:
                  type: string
                  example: support
      responses:
        '200':
          description: Record stored
    get:
      summary: Get a record for a subject by key
      parameters:
        - in: path
          name: subjectId
          required: true
          schema:
            type: string
        - in: path
          name: key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Record found
        '404':
          description: Not found
