name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      GRADLE_TERMS_OF_SERVICE_ACCEPTED: "yes"
      GRADLE_TERMS_OF_SERVICE_URL: "https://gradle.com/terms-of-service"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper (IPv4, local checksum)
        run: |
          set -e
          PROP_FILE="gradle/wrapper/gradle-wrapper.properties"
          DIST_URL=$(grep '^distributionUrl=' "$PROP_FILE" | sed 's/distributionUrl=//')
          SHA=$(grep '^distributionSha256Sum=' "$PROP_FILE" | sed 's/distributionSha256Sum=//')

          echo "Distribution: $DIST_URL"
          echo "Expected SHA256: $SHA"

          # Download via IPv4 to avoid ENETUNREACH
          curl -4 -L "$DIST_URL" -o gradle-dist.zip

          ACTUAL=$(sha256sum gradle-dist.zip | awk '{print $1}')
          echo "Actual SHA256: $ACTUAL"

          if [ "$ACTUAL" != "$SHA" ]; then
            echo "Gradle distribution checksum mismatch!"
            exit 1
          fi


      - name: Build (tests included) with retry (IPv4)
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dhttps.protocols=TLSv1.2"
        run: |
          for i in 1 2 3; do
            ./gradlew build --no-daemon && break
            echo "Gradle build failed (attempt $i). Retrying in 15s..."
            sleep 15
          done

      - name: Assemble bootable jar
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dhttps.protocols=TLSv1.2"
        run: ./gradlew bootJar --no-daemon

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdpr-kv-jar
          path: build/libs/*.jar
          if-no-files-found: error