name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      GRADLE_TERMS_OF_SERVICE_ACCEPTED: "yes"
      GRADLE_TERMS_OF_SERVICE_URL: "https://gradle.com/terms-of-service"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Verify Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      # Robust build with retries (handles transient network hiccups)
      - name: Build (tests included) with retry
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dhttps.protocols=TLSv1.2"
        run: |
          for i in 1 2 3; do
            ./gradlew build --no-daemon && break
            echo "Gradle build failed (attempt $i). Retrying in 15s..."
            sleep 15
          done

      - name: Assemble bootable jar
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dhttps.protocols=TLSv1.2"
        run: ./gradlew bootJar --no-daemon

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdpr-kv-jar
          path: build/libs/*.jar
          if-no-files-found: error